### ISSUE TITLE
Could you publish the code?

### ISSUE THREAD

**Issue by aug08** [CodeBreathing/DMMR#1]
Dear authors, we are interested in your paper so much. Thank you for providing such a good solution for cross-subject EEG emotion recognition. Could you publish the code? Thank you very much!

**Comment by xuxiran** [comment]
How excellent work! Thank you for providing such a good solution for cross-subject EEG emotion recognition. Considering that the article can already be accessed on the official website, could you publish the code? Thank you very much!

**Comment by CodeBreathing** [comment]
The code corresponding to the DMMR paper has been open-sourced. Thank you for your attention to our work.

**Comment by CodeBreathing** [comment]
The code corresponding to the DMMR paper has been open-sourced. Thank you for your attention to our work.
